config/routes.rb
Rails.application.routes.draw do
  root 'public/tops#top'
  get :about, to: 'public/tops#about', as: 'about'

  # ユーザー登録
  get  :signup, to: 'public/users#new',  as: 'signup'
  post :signup, to: 'public/users#create'

  scope module: :public do
    # ユーザー
    resources :users, except: [:new, :create]
  end

  # セッション管理
  get    :login,  to: 'sessions#new'
  post   :login,  to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/public.rb
module Public
  def self.table_name_prefix
    "public_"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # セッションのヘルパーをインクルード
  # https://railstutorial.jp/chapters/basic_login?version=5.1#sec-logging_in
  # 基底クラスであるApplicationControllerでインクルードする事で、全てのコントローラでこのモジュールを使用可能になる。
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = Public::User.find_by( email: params[:email].downcase )
    # ユーザーの存在チェック、且つパスワードの整合性をチェック
    if user && user.authenticate( params[:password] )
      log_in user
      # remember user
      params[:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user_path( user )
    else
      # flash[:danger] = 'メールアドレス、もしくはパスワードが正しくないようです。'
      # flash.nowは、リクエストが発生したタイミングで消失する。
      flash.now[:danger] = 'メールアドレス、もしくはパスワードが正しくないようです。再度入力をお試しください。'
      render 'new'
    end
  end

  def destroy
    # log_out
    log_out if logged_in? # ログイン中のユーザーのみログアウトを実行できるようにする。
    redirect_to root_url
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  # トップページ
  def index
    @hypertext = "<b>大文字で出力</b>"
    @prod = 5
  end

  # アバウトページ
  def about
    # ページのタイトルを定義
    @page_title = '概要'
    # なぜかテンプレートで定義すると読み込めないので調査が必要。
  end

  # テスト
  def test
  end

  # お試しメソッド
  def some_function(arg1, arg2)
    # rubyは最後に評価された式がreturnされる。明示的にreturnしてもエラーにはならない。
    arg1 + arg2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ブラウザタブに表示するテキストを返却する。
  def browser_tab_text(page_title)
    title = 'Dancers'
    # if page_title # 左の条件で判定しようとするとうまくいかない。
    # nilとfalseについて確認しといた方が良さそう。
    if page_title.empty?
      # page_title + ' - ' + title
      title
    else
      # title
      page_title + ' - ' + title
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in( user )
    session[:user_id] = user.id
  end

  def remember( user )
    user.set_remember_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= Public::User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = Public::User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    ! current_user.nil?
  end

  def forget( user )
    user.remove_remember_token
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/common/_error_messages.html.slim
- if @user.errors.any?
- @user.errors.full_messages.each do |msg|
  br/
  = msg

app/views/common/_footer.html.slim
.foot_wrap
  span.foot_wrap-inner
    / p © Dancers

  = link_to '概要', about_path

  / 統合テストの失敗を確認するために存在しないルーティングを指定する
  / = link_to '概要', hoge_path
  / 上記の記述でテストに失敗する事を確認。

app/views/common/_header.html.slim
div.head_wrap
  h2.head_title = link_to 'Dancers', '/'
  span.head_title-small BETA
  nav.gNav
    ul
      - if logged_in?
        li.head_list = link_to 'マイページ', user_path( current_user )
        / li.head_list = link_to '編集', edit_user_path
        li.head_list = button_to 'ログアウト', logout_path, method: :delete
        / link_toだと動かないが、button_toだとなぜか動く。おそらく以下が同様の事例
        / https://teratail.com/questions/268094
        / https://www.google.com/search?q=method%3A+%3Adelete+%E5%8A%B9%E3%81%8B%E3%81%AA%E3%81%84&rlz=1C5CHFA_enJP911JP911&oq=method%3A+%3Adelete+%E5%8A%B9%E3%81%8B%E3%81%AA%E3%81%84&aqs=chrome..69i57j69i58.6132j0j7&sourceid=chrome&ie=UTF-8
        / li.head_list = link_to 'ログアウト', logout_path, method: :delete
      - else
        li.head_list = link_to 'ログイン', login_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# 各ページ毎にページタイトルを取得 %>
    <%# https://railstutorial.jp/chapters/rails_flavored_ruby?version=5.1#code-application_layout_full_title %>
    <title><%= browser_tab_text( yield(:title) ) %></title>
    <%# この記述いらない気が。。。 %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# CSRF %>
    <%= csrf_meta_tags %>
    <%# コンテンツセキュリティポリシーのタグ。初期状態では使用しない。 %>
    <%= csp_meta_tag %>
    <%# スタイルシートの取得 %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%# ヘッダー %>
    <header>
      <%= render "common/header" %>
    </header>
    <%# メインの出力 %>
    <main>
      <div class='container'>
        <%# フラッシュメッセージ %>
        <% flash.each do |key, message| %>
          <% if key == 'danger' %>
            <div class="flash__danger">
          <% else %>
            <div>
          <% end %>
              <%= message %>
            </div>
        <% end %>
        <%# コンテンツ本体 %>
        <%= yield %>
      </div>
    </main>
    <%# フッター %>
    <footer class='footer'>
      <%= render "common/footer" %>
    </footer>
  </body>
</html>

app/views/top/about.html.erb
<h1>about page</h1>

app/views/top/about.html.slim
<h1>色々やってみるページ</h1>

= form_with url: '/about', method: :post do |form|
  = form.label :piyopiyo, "検索:"
  = form.text_field :piyopiyo
  = form.submit 'search'

app/views/top/index.html.slim
h1 slimのテスト中

== @hypertext

/ https://railsdoc.com/page/link_to
/ link_toを使うと簡単にaタグを作成できる
= link_to 'aboutへ移動', '/about', class: 'menu'

- 5.times do |i|
  p = i
  / この書き方pにiを代入してるみたいで結構可読性低い。

= @prod